//Bisimillahirrahmanirrahim
package ui;

import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import src.MultiDimList;
import src.Node;

/**
 *
 * @author bismih
 */
public class Main extends JFrame {
    //? generate all block for the first time
    private static void generateBlock() {
        int a_x = 100;
        int a_y = 150;
        int size = 41;
        for (int i = 0; i < x + 1; i++) {
            for (int j = 0; j < y + 1; j++) {
                block_l[i][j] = new Block();
                block_l[i][j].setSize(size, size);
                block_l[i][j].setLocation(a_x + i * (size + 10), a_y + j * (size + 10));
                frame.add(block_l[i][j]);
                block_l[i][j].setVisible(true);
            }
        }
    }
    //? update all block
    private void updateBlock(MultiDimList<Integer> l, Block block_l[][]) {
        Node<Integer> tmp = l.head;
        Node<Integer> tmpH = l.head;
        int j = y;
        clearBlocks(block_l);
        while (tmpH != null) {
            while (tmp != null) {
                int x_co=x-tmp.x;
                int val = tmp.data;

                block_l[x_co][j].changeVal(val + "");
                block_l[x_co][j].setBackground(getColor(val));
                j--;
                tmp = tmp.up;
            }
            j = y;
            tmpH = tmpH.left;
            tmp = tmpH;
        }
    }
    //? simple minumum method
    private int min(int a, int b) {
        return a < b ? a : b;
    }

    //? calculating color by value
    private Color getColor(int value) {
        int r, g, b;
        //? this mat formul give how close the value is to 2048 and do nomalization
        r = min(255, (int) (Math.log(value) / Math.log(2048) * 255) + 30);
        g = min(255, Math.abs((int) ((Math.log(value) - Math.log(81)) / (Math.log(2048) - Math.log(64)) * 255)));
        b = min(255, Math.abs((int) ((Math.log(value) - Math.log(41)) / (Math.log(2048) - Math.log(16)) * 255)));
        System.out.println(r + " " + g + " " + " " + b);
        return new Color(r, g, b);
    }
    //? reset all block
    private void clearBlocks(Block block_l[][]) {
        for (int i = 0; i < x + 1; i++) {
            for (int j = 0; j < y + 1; j++) {
                block_l[i][j].changeVal("");
                block_l[i][j].setBackground(new Color(204, 255, 255));
            }
        }
    }

    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        bt_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 571));

        bt_next.setText("Next");
        bt_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_next)
                                .addGap(21, 21, 21)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(bt_next)
                                .addGap(42, 42, 42)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(390, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //? button for next step
    private void bt_nextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bt_nextActionPerformed
        int index[] = { 4, 1, 3, 2, 0, 3, 0, 4,
                4, 3, 2, 2, 1, 3, 2, 4, 0, 2, 3, 1,
                1, 1, 1, 3, 2, 2, 2, 2, 2, 3, 3 };

        int vals[] = { 2, 2, 4, 2, 4, 2, 4, 8,
                8, 32, 2, 64, 16, 64, 32, 16, 16,
                32, 64, 8, 4, 2, 2, 2, 64, 32,
                16, 8, 8, 4, 8 };

        try {
            l.addProces(vals[count], index[count]);
            count++;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Game Over");
        }
        updateBlock(l, block_l);
    }// GEN-LAST:event_bt_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new Main().setVisible(true);
                frame.setVisible(true);
                generateBlock();
            }
        });
    }

    private static int x = 4, y = 6;
    private int count = 0;
    private static MultiDimList<Integer> l = new MultiDimList<>();
    private static Block block_l[][] = new Block[5][7];
    private static JFrame frame = new Main();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_next;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
